peripheral.find("modem", rednet.open)
rednet.broadcast(nil, "netboot-request")
local _, payload, _ = rednet.receive("netboot-response", 5)
assert(payload, "no netboot server")
load(payload, "=netboot", nil, _ENV)()
