print("Booting from network...")
peripheral.find("modem", rednet.open)
rednet.broadcast(nil, "netboot-request")
local _, payload, _ = rednet.receive("netboot-response")
load(payload, "=netboot", nil, _ENV)()
