local k = require "ru".text.to_koi_inner

return require "keyboard.simple" {
    grave  = { k'3', k'#' },
    one    = { '1', '!' },
    two    = { '2', '"' },
    three  = { '3', '#' },
    four   = { '4', ';' },
    five   = { '5', '%' },
    six    = { '6', ':' },
    seven  = { '7', '?' },
    eight  = { '8', '*' },
    nine   = { '9', '(' },
    zero   = { '0', ')' },
    minus  = { '-', '_' },
    equals = { '=', '+' },

    q = { k'j', k'J' },
    w = { k'c', k'C' },
    e = { k'u', k'U' },
    r = { k'k', k'K' },
    t = { k'e', k'e' },
    y = { k'n', k'N' },
    u = { k'g', k'G' },
    i = { k'{', k'[' },
    o = { k'}', k']' },
    p = { k'z', k'Z' },
    leftBracket  = { k'h', k'H' },
    rightBracket = { k'\x7F', k'_' },
    backslash    = { '\\', '/' },

    a = { k'f', k'F' },
    s = { k'y', k'Y' },
    d = { k'w', k'W' },
    f = { k'a', k'A' },
    g = { k'p', k'P' },
    h = { k'r', k'R' },
    j = { k'o', k'O' },
    k = { k'l', k'L' },
    l = { k'd', k'D' },
    semicolon  = { k'v', k'V' },
    apostrophe = { k'|', k'\\' },

    z = { k'q', k'Q' },
    x = { k'~', k'^' },
    c = { k's', k'S' },
    v = { k'm', k'M' },
    b = { k'i', k'I' },
    n = { k't', k'T' },
    m = { k'x', k'X' },
    comma  = { k'b', k'B' },
    period = { k'`', k'@' },
    slash  = { '.', ',' },

    space = { ' ' },
}
