local k = require "ru".text.to_koi_inner

return require "keyboard.simple" {
    grave  = { '`', '~' },
    one    = { '1', '!' },
    two    = { '2', '@' },
    three  = { '3', '#' },
    four   = { '4', '$' },
    five   = { '5', '%' },
    six    = { '6', '^' },
    seven  = { '7', '&' },
    eight  = { '8', '*' },
    nine   = { '9', '(' },
    zero   = { '0', ')' },
    minus  = { '-', '_' },
    equals = { '=', '+' },

    q = { k'{', k'[', k'}', k']' },
    w = { k'v', k'V' },
    e = { k'f', k'F' },
    r = { k'p', k'P' },
    t = { k'b', k'B' },
    y = { k'y', k'Y', k'\x7F', k'_' },
    u = { k'l', k'L' },
    i = { k'u', k'U', k'`', k'@' },
    o = { k'j', k'J' },
    p = { ';', ':' },
    leftBracket  = { '[', '{', '\xAB' },
    rightBracket = { ']', '}', '\xBB' },
    backslash    = { '\\', '|' },

    a = { k'a', k'A', k'q', k'Q' },
    s = { k'r', k'R' },
    d = { k's', k'S' },
    f = { k't', k'T' },
    g = { k'g', k'G' },
    h = { k'm', k'M' },
    j = { k'n', k'N' },
    k = { k'e', k'E', k'|', k'\\' },
    l = { k'i', k'I' },
    semicolon  = { k'o', k'O', k'3', k'#' },
    apostrophe = { "'", '"', k'x', k'X' },

    z = { k'~', k'^' },
    x = { k'c', k'C' },
    c = { k'd', k'D' },
    v = { k'w', k'W' },
    b = { k'z', k'Z' },
    n = { k'k', k'K' },
    m = { k'h', k'H' },
    comma  = { ',', '<' },
    period = { '.', '>' },
    slash  = { '/', '?', '\xBF' },

    space = { ' ' },
}
