local compressed, bytes = ...

local byte_cache = {}
for i = 1, #bytes, 2 do
    for c = bytes:byte(i), bytes:byte(i + 1) do
        table.insert(byte_cache, c)
    end
end

local rle = 1

local bwt = {}
local bwt_pos = 0
local counts = {}
for c = -1, 255 do
    counts[c] = 0
end
local pos_in_char = {}

local state = 0
local byte_pos = 1
local symbol

-- This definition needs to be split because initializers cannot refer to locals they define, even
-- inside closures.
local tables
tables = {
    -- This closure is generated by stage 1 for each table.
    TABLE_START(),
    function()
        while bwt_pos < __LIMIT__ do
            while state < 2 ^ 21 do
                state = state * 2 ^ 32 + string.unpack("<I", compressed, byte_pos)
                byte_pos = byte_pos + 4
            end
            local bits = state % 2 ^ 14
            DECODE_SYMBOL(bits,symbol,state)
            if symbol < 2 then
                rle = rle * 2 + symbol
            elseif symbol > #byte_cache then
                return tables[symbol - #byte_cache]()
            else
                if rle > 1 then
                    local byte = byte_cache[1]
                    local count = rle - 1
                    local last_count = counts[byte]
                    for i = 1, count do
                        bwt[bwt_pos + i] = byte
                        pos_in_char[bwt_pos + i] = last_count + i
                    end
                    counts[byte] = last_count + count
                    bwt_pos = bwt_pos + count
                    rle = 1
                end
                bwt_pos = bwt_pos + 1
                local byte = byte_cache[symbol]
                table.move(byte_cache, 1, symbol - 1, 2)
                byte_cache[1] = byte
                bwt[bwt_pos] = byte
                local new_count = counts[byte] + 1
                counts[byte] = new_count
                pos_in_char[bwt_pos] = new_count
            end
        end
    end,
    TABLE_END()
}
tables[1]()

counts[bwt[bwt_pos]] = counts[bwt[bwt_pos]] - 1
bwt[bwt_pos] = nil

for c = 1, 255 do
    counts[c] = counts[c] + counts[c - 1]
end
table.move(counts, -1, 254, 0)
local s = {}
local pos = __SHIFT__
for i = #bwt, 1, -1 do
    local c = bwt[pos]
    s[i] = c
    pos = pos_in_char[pos] + counts[c]
end
return string.char(table.unpack(s))
