local compressed, cache = ...

local alphabet = { cache:byte(1, #cache) }
table.sort(alphabet)
cache = { cache:byte(1, #cache) }

local rle, ranks, ranks_pos, state, byte_pos, symbol_pointers, symbol_idx, symbol =
    1, -- rle
    {}, -- ranks
    0, -- ranks_pos
    0, -- state
    1, -- byte_pos
    {}, -- symbol_pointers
    1 -- symbol_idx

-- This definition needs to be split because initializers cannot refer to locals they define, even
-- inside closures.
local tables
tables = {
    -- This closure is generated by stage 1 for each table.
    TABLE_START(),
    function()
        while ranks_pos < __LIMIT__ do
            while state < 2 ^ 21 do
                state = state * 2 ^ 32 + string.unpack("<I", compressed, byte_pos)
                byte_pos = byte_pos + 4
            end
            local bits = state % 2 ^ 14
            DECODE_SYMBOL(bits,symbol,state)
            if symbol < 2 then
                rle = rle * 2 + symbol
            elseif symbol > #alphabet + 1 then
                return tables[symbol - #alphabet - 1]()
            else
                ranks_pos = ranks_pos + rle - 1
                rle = 1
                if symbol == #alphabet + 1 then
                    -- leader
                    symbol_pointers[alphabet[symbol_idx]] = ranks_pos
                    symbol_idx = symbol_idx + 1
                else
                    ranks_pos = ranks_pos + 1
                    ranks[ranks_pos] = symbol
                end
            end
        end
    end,
    TABLE_END()
}
tables[1]()


local bwt = {}
local transition = {}

for i = 1, ranks_pos - 1 do
    local byte = cache[1]
    bwt[i] = byte

    symbol_pointers[byte] = symbol_pointers[byte] + 1
    transition[i] = symbol_pointers[byte]

    local rank = ranks[symbol_pointers[byte]]
    if rank then
        table.move(cache, 2, rank, 1)
        cache[rank] = byte
    end
end

local s = {}
local pos = __SHIFT__
for i = #bwt, 1, -1 do
    s[i] = bwt[pos]
    pos = transition[pos]
end
return string.char(table.unpack(s))
