return {
	-- Vanilla discs
	["minecraft:music_disc_13"] = "C418 - 13",
	["minecraft:music_disc_cat"] = "C418 - cat",
	["minecraft:music_disc_blocks"] = "C418 - blocks",
	["minecraft:music_disc_chirp"] = "C418 - chirp",
	["minecraft:music_disc_far"] = "C418 - far",
	["minecraft:music_disc_mall"] = "C418 - mall",
	["minecraft:music_disc_mellohi"] = "C418 - mellohi",
	["minecraft:music_disc_stall"] = "C418 - stall",
	["minecraft:music_disc_strad"] = "C418 - strad",
	["minecraft:music_disc_ward"] = "C418 - ward",
	["minecraft:music_disc_11"] = "C418 - 11",
	["minecraft:music_disc_wait"] = "C418 - wait",
	["minecraft:music_disc_pigstep"] = "Lena Raine - Pigstep",
	["minecraft:music_disc_otherside"] = "Lena Raine - otherside",
	["minecraft:music_disc_creator"] = "Lena Raine - Creator",
	["minecraft:music_disc_creator_music_box"] = "Lena Raine - Creator (Music Box)",
	["minecraft:music_disc_5"] = "Samuel Åberg - 5",
	["minecraft:music_disc_relic"] = "Aaron Cherof - Relic",
	["minecraft:music_disc_precipice"] = "Aaron Cherof - Precipice",
	["minecraft:music_disc_tears"] = "Amos Roddy - Tears",
	["minecraft:music_disc_lava_chicken"] = "Hyper Potions - Tears",

	-- Modded
	["additionaladditions:music_disc_0308"] = "adoghr - 0308",
	["additionaladditions:music_disc_1007"] = "adoghr - 1007",
	["additionaladditions:music_disc_1507"] = "adoghr - 1507",
	["snowyspirit:music_disc_winter"] = "STiiX - A Carol",
	["supplementaries:music_disc_heave_ho"] = "Hlzfss - Heave Ho!",
	["betterend:music_disc_strange_and_alien"] = "Firel - Strange And Alien",
	["betterend:music_disc_grasping_at_stars"] = "Firel - Grasping At Stars",
	["betterend:music_disc_endseeker"] = "Firel - Endseeker",
	["betterend:music_disc_eo_dracona"] = "Firel - Eo Dracona",
	["spectrum:music_disc_discovery"] = "DaveJF - The Mist",
	["spectrum:music_disc_credits"] = "Radiarc - Irrelevance Fading",
	["spectrum:music_disc_divinity"] = "Proper Motions - Everreflective",
}
